using System.Collections.Generic;

namespace Overlayer.Utils;

public class Tooltip
{
    public static string GetTooltip(string key) {
        if(string.IsNullOrEmpty(key)) {
            return null;
        }

        string keyUpper = key.ToUpperInvariant();

        string langKey = "TOOLTIP_" + keyUpper;
        string localized = Main.Lang.Get(langKey, null);
        if(!string.IsNullOrEmpty(localized)) {
            return localized;
        }

        if(tooltip.TryGetValue(keyUpper, out var staticTip) && !string.IsNullOrEmpty(staticTip)) {
            return staticTip;
        }

        return null;
    }

    public static Dictionary<string, string> tooltip = new() {
        ["ABSMAXXACCURACY"] = "The highest achievable Absolute Max XAccuracy in the current tile(Excluding checkpoints)",
        ["ABSXACCURACY"] = "Absolute Max XAccuracy(Excluding checkpoints)",
        ["ACCURACY"] = "Accuracy(when perfect: 100+0.01%)",
        ["ACTUALPROGRESS"] = "Current Actual Progress based on time",
        ["ARTIST"] = "Composer of the song",
        ["ARTISTRAW"] = "Composer of the song (with rich tags)",
        ["ATTEMPTS"] = "Shows Attempts. Only effective at CLS and official levels.",
        ["AUTHOR"] = "Level creator",
        ["AUTHORRAW"] = "Level creator (with rich tags)",
        ["BESTPROGRESS"] = "Best progress of the level",
        ["CELP"] = "Current Early Perfect + Late Perfect",
        ["CEP"] = "Current Early Perfect",
        ["CFAST"] = "Fast judgment in Current difficulty",
        ["CHECKPOINTUSED"] = "Number of checkpoints used",
        ["CHIT"] = "Current Hit",
        ["CHITRAW"] = "Current Hit Raw",
        ["CLP"] = "Current Late Perfect",
        ["COLORRANGE"] = "You can adjust the color from any color to any color you want based on a specific tag. Use with <color>.",
        ["COMBO"] = "Combo count",
        ["CP"] = "Current Perfect",
        ["CSLOW"] = "Slow judgment in Current difficulty",
        ["CT"] = "Current Too Early + Current Too Late",
        ["CTE"] = "Current Too Early",
        ["CTL"] = "Current Too Late",
        ["CURBPM"] = "Current BPM",
        ["CURBPMWITHOUTPITCH"] = "Current BPM (without pitch)",
        ["CURCHECKPOINT"] = "Current checkpoint number",
        ["CURDAY"] = "Current day of song",
        ["CURHOUR"] = "Current hour of song",
        ["CURMILLISECOND"] = "Current millisecond of song",
        ["CURMINUTE"] = "Current minute of song",
        ["CURSECOND"] = "Current second of song",
        ["CURTILE"] = "Current tile number",
        ["CV"] = "Current Very Early + Current Very Late",
        ["CVE"] = "Current Very Early",
        ["CVL"] = "Current Very Late",
        ["DAY"] = "Day on current computer",
        ["DAYS"] = "All days so far",
        ["DEATHS"] = "The total number of planet explosions on the current map",
        ["DEFAULTTEXTCOLOR"] = "Default text color of the level",
        ["DEFAULTTEXTSHADOWCOLOR"] = "Default text shadow color of the level",
        ["DEVELOPER"] = "Square & Kkitut",
        ["DIFFICULTY"] = "Current Difficulty",
        ["DIFFICULTYRAW"] = "Fixed difficulty return value regardless of language setting",
        ["EASEDVALUE"] = "When the tag value changes, the tag value changes according to the speed.",
        ["EDITORPITCH"] = "Pitch set in the LevelEditor (displayed as 1 when 100%)",
        ["EPHEX"] = "EarlyPerfect Hex Color",
        ["FAIL"] = "MissCount + Overload",
        ["FMHEX"] = "Miss Hex Color",
        ["FOHEX"] = "Overload Hex Color",
        ["FPS"] = "Current FPS of ADOFAI",
        ["FRAME"] = "Frame",
        ["FRAMETIME"] = "Time difference between the previous frame and the current frame in ms",
        ["GCMEMALLOCRATE"] = "Shows the allocation rate of memory by the Garbage Collector in MB per tick",
        ["GCMEMALLOCRATEGB"] = "Shows the allocation rate of memory by the Garbage Collector in GB per tick",
        ["GCMEMALLOCRATEKB"] = "Shows the allocation rate of memory by the Garbage Collector in KB per tick",
        ["GCMEMUSAGE"] = "Shows the total memory used by the Garbage Collector in MB",
        ["GCMEMUSAGEGB"] = "Shows the total memory used by the Garbage Collector in GB",
        ["GCMEMUSAGEKB"] = "Shows the total memory used by the Garbage Collector in KB",
        ["HOUR"] = "Hour on current computer",
        ["HOURS"] = "Total hours so far",
        ["ISAUTOENABLED"] = "Displays true if auto is enabled, false otherwise",
        ["ISNOFAILENABLED"] = "Displays true if No-fail Mode is enabled, false if disabled",
        ["ISOLDAUTOENABLED"] = "Displays true if Old Auto is enabled, false if disabled",
        ["ISPRACTICEMODEENABLED"] = "Displays true if practice mode is enabled, false otherwise",
        ["ISSPEEDTRIALENABLED"] = "Displays true if Speed Trial Mode is enabled, false otherwise.\nOnly works on CLS and official levels.",
        ["ISSTARTED"] = "Displays false if not started, or true if started by pressing any key",
        ["LEFTTILE"] = "Number of tiles left",
        ["LELP"] = "Lenient Early Perfect + Lenient Late Perfect",
        ["LEP"] = "Lenient Early Perfect",
        ["LEVELNAMETEXT"] = "The name text displayed at the top of the level.",
        ["LEVELNAMETEXTCOLOR"] = "The color of the text displayed at the top of the level.",
        ["LEVELNAMETEXTRAW"] = "The name text displayed at the top of the level. (with rich tags)",
        ["LEVELNAMETEXTSHADOW"] = "The shadow color of the text displayed at the top of the level.",
        ["LFAST"] = "Fast judgment in Lenient difficulty",
        ["LHIT"] = "Lenient Hit",
        ["LHITRAW"] = "Lenient Hit Raw",
        ["LLP"] = "Lenient Late Perfect",
        ["LMARGINCOMBO"] = "Lenient judgment of MarginCombo",
        ["LMARGINCOMBOS"] = "Lenient judgment of MarginCombos",
        ["LMARGINMAXCOMBO"] = "Lenient judgment of MarginMaxCombo",
        ["LMARGINMAXCOMBOS"] = "Lenient judgment of MarginMaxCombos",
        ["LP"] = "Lenient Perfect",
        ["LPHEX"] = "LatePerfect Hex Color",
        ["LSCORE"] = "Lenient difficulty score",
        ["LSLOW"] = "Slow judgment in Lenient difficulty",
        ["LTE"] = "Lenient Too Early",
        ["LTL"] = "Lenient Too Late",
        ["LVE"] = "Lenient Very Early",
        ["LVL"] = "Lenient Very Late",
        ["MARGINCOMBO"] = "Displays the combo for a single judgment\n(ex: {MarginCombo:VeryLate})",
        ["MARGINCOMBOS"] = "Displays all combos for multiple judgments\n(ex: {MarginCombos:VeryLate|VeryEarly})",
        ["MARGINMAXCOMBO"] = "Displays the maximum combo for a single judgment\n(ex: {MarginMaxCombo:VeryLate})",
        ["MARGINMAXCOMBOS"] = "Displays all maximum combos for multiple judgments\n(ex: {MarginMaxCombos:VeryLate|VeryEarly})",
        ["MARGINSCALE"] = "Level's judgment range",
        ["MAXACCURACY"] = "The highest achievable Accuracy in the current tile",
        ["MAXCOMBO"] = "Maximum Combo",
        ["MAXXACCURACY"] = "The highest achievable XAccuracy in the current tile",
        ["MILLISECOND"] = "Milliseconds on current computer",
        ["MILLISECONDS"] = "Total milliseconds so far",
        ["MINUTE"] = "Minutes on current computer",
        ["MINUTES"] = "Total minutes so far",
        ["MIPANYANG"] = "Goodbye, Forever.",
        ["MISSCOUNT"] = "Number of Misses",
        ["MODVERSION"] = "Current version of Overlayer",
        ["MONTH"] = "Month on current computer",
        ["MOVINGMAN"] = "You can animate text on criterion certain tags. Used with <size>.",
        ["MPHEX"] = "Multipress Hex Color",
        ["MULTIPRESS"] = "Number of Multipresses",
        ["MULTIPRESSCOUNTER"] = "The percentage of the multipress gauge.",
        ["MULTIPRESSCOUNTERRAW"] = "The raw internal value of the multipress gauge in the game.",
        ["NELP"] = "Normal Early Perfect + Normal Late Perfect",
        ["NEP"] = "Normal Early Perfect",
        ["NFAST"] = "Fast judgment in Normal difficulty",
        ["NHIT"] = "Normal Hit",
        ["NHITRAW"] = "Normal Hit Raw",
        ["NLP"] = "Normal Late Perfect",
        ["NMARGINCOMBO"] = "Normal judgment of MarginCombo",
        ["NMARGINCOMBOS"] = "Normal judgment of MarginMaxCombo",
        ["NMARGINMAXCOMBO"] = "Normal judgment of MarginMaxCombos",
        ["NMARGINMAXCOMBOS"] = "Normal judgment of MarginMaxCombos",
        ["NP"] = "Normal Perfect",
        ["NSCORE"] = "Normal difficulty score",
        ["NSLOW"] = "Slow judgment in Normal difficulty",
        ["NT"] = "Normal Too Early + Normal Too Late",
        ["NTE"] = "Normal Too Early",
        ["NTL"] = "Normal Too Late",
        ["NV"] = "Normal Very Early + Normal Very Late",
        ["NVE"] = "Normal Very Early",
        ["NVL"] = "Normal Very Late",
        ["OA"] = "Official Perfect (Only Auto)",
        ["OELP"] = "Official Early Perfect + Official Late Perfect",
        ["OEP"] = "Official Early Perfect",
        ["OFAST"] = "Fast judgment in Official",
        ["OLP"] = "Official Late Perfect",
        ["OP"] = "Official Perfect",
        ["OPP"] = "Official Perfect (Only Player)",
        ["OSLOW"] = "Slow judgment in Official",
        ["OT"] = "Official Too Early + Official Too Late",
        ["OTE"] = "Official Too Early",
        ["OTL"] = "Official Too Late",
        ["OV"] = "Official Very Early + Official Very Late",
        ["OVE"] = "Official Very Early",
        ["OVERLOADCOUNTER"] = "The percentage of the overload gauge.",
        ["OVERLOADCOUNTERRAW"] = "The raw internal value of the overload gauge in the game.",
        ["OVERLOADS"] = "Number of Overloads",
        ["OVL"] = "Normal Very Late",
        ["PHEX"] = "Perfect Hex Color",
        ["PITCH"] = "Speed set in CLS (displayed as 1 when at 1x speed)",
        ["PROGRESS"] = "Current progress",
        ["RAINBOW"] = "Rainbow",
        ["RECKPS"] = "Recommended KPS",
        ["RECKPSWITHOUTPITCH"] = "Recommended KPS (without pitch)",
        ["SCORE"] = "Current difficulty score",
        ["SECOND"] = "Seconds on current computer",
        ["SECONDS"] = "Total seconds so far",
        ["SELP"] = "Strict Early Perfect + Strict Late Perfect",
        ["SEP"] = "Strict Early Perfect",
        ["SFAST"] = "Fast judgment in Strict difficulty",
        ["SHIT"] = "Strict Hit",
        ["SHITRAW"] = "Strict Hit Raw",
        ["SLP"] = "Strict Late Perfect",
        ["SMARGINCOMBO"] = "Strict judgment of MarginCombo",
        ["SMARGINCOMBOS"] = "Strict judgment of MarginCombos",
        ["SMARGINMAXCOMBO"] = "Strict judgment of MarginMaxCombo",
        ["SMARGINMAXCOMBOS"] = "Strict judgment of MarginMaxCombos",
        ["SP"] = "Strict Perfect",
        ["SPECIALPLAYMARK"] = "Displays a special mark based on your play performance:\nPP = perfect  FC+ = no miss\nFC = full combo  XX = no special mark",
        ["SSCORE"] = "Strict difficulty score",
        ["SSLOW"] = "Slow judgment in Strict difficulty",
        ["ST"] = "Strict Too Early + Strict Too Late",
        ["STARTPROGRESS"] = "Progress of start tile",
        ["STARTTILE"] = "Start tile number",
        ["STE"] = "Strict Too Early",
        ["STL"] = "Strict Too Late",
        ["SV"] = "Strict Very Early + Strict Very Late",
        ["SVE"] = "Strict Very Early",
        ["SVL"] = "Strict Very Late",
        ["TARGETFPS"] = "Target FPS of ADOFAI",
        ["TEHEX"] = "TooEarly Hex Color",
        ["TILEANGLE"] = "The angle of the current tile",
        ["TILEBPM"] = "Tile BPM",
        ["TILEBPMWITHOUTPITCH"] = "Tile BPM (without pitch)",
        ["TILEENTRYANGLE"] = "Indicates the entry angle from the entry tile to the current tile.",
        ["TILEEXITANGLE"] = "Indicates the exit angle from the current tile to the next tile.",
        ["TIMING"] = "Error range showing the timing of keystrokes in ms from the center of the tile",
        ["TIMINGAVG"] = "Average of Timing",
        ["TITLE"] = "Title of the song",
        ["TITLERAW"] = "Title of the song (with rich tags)",
        ["TLHEX"] = "TooLate Hex Color",
        ["TOTALCHECKPOINTS"] = "Total number of checkpoints",
        ["TOTALDAY"] = "Total day of song",
        ["TOTALHOUR"] = "Total hour of song",
        ["TOTALMILLISECOND"] = "Total millisecond of song",
        ["TOTALMINUTE"] = "Total minute of song",
        ["TOTALSECOND"] = "Total second of song",
        ["TOTALTILE"] = "Total number of tiles",
        ["UNITYMEMUSAGE"] = "Shows the total memory used by Unity, not including the entire process memory",
        ["UNITYMEMUSAGEGB"] = "Shows the total memory used by Unity in GB, not including the entire process memory",
        ["UNITYMEMUSAGEKB"] = "Shows the total memory used by Unity in KB, not including the entire process memory",
        ["VEHEX"] = "VeryEarly Hex Color",
        ["VLHEX"] = "VeryLate Hex Color",
        ["XACCURACY"] = "XAccuracy(when pure perfect: 100)",
        ["YEAR"] = "Year on current computer",
    };
}